---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart A
```{r}
rest_inspec_df=
  rest_inspec |>
  janitor::clean_names()|>
  filter(str_detect(grade_date, "2019"))|>
  filter(boro %in% c("Staten Island"))

rest_inspec_df|>
  filter(grade %in% c("A", "B", "C"))|>
  count(grade) |>
  mutate(grade = fct_reorder(grade, c("A", "B", "C")))|>
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar")|>
  layout(title = "2019 Inspection Grades in Staten Island",
         xaxis = list(title ="Grade"),
         yaxis = list(title = "Count"))
```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec_df |>
  drop_na(latitude, longitude)|>
  filter(latitude != "0")|>
  filter(zipcode == "10307")|>
  group_by(camis)|>
  mutate(
    text_label = str_c("Restaurant Identifier: ", camis, "\nName of Business: ", dba,
      "\nType of Cuisine: ", cuisine_description)
    )|>
  plot_ly(
    x = ~latitude, y = ~longitude, 
    text = ~text_label, color = ~cuisine_description, 
    type = "scatter", colors = "viridis", mode = "markers", alpha = 0.5)|>
  layout(title = "2019 Restaurant Locations in Zipcode 10307")
```

### Chart C

```{r}
rest_inspec_df |>
  separate(
    inspection_type, 
    into = c("inspec_program", "inspec_type"), sep = "/")|>
  group_by(inspec_type, inspec_program, score)|>
  plot_ly(x = ~inspec_type, y = ~score,
         color = ~inspec_program, type = "box", colors = "viridis")|>
    layout(boxmode = "group", title = "Distribution of Inspection Scores",
         xaxis = list(title ="Type of Inspection"),
         yaxis = list(title = "Scores"))
```

